### ISSUE TITLE
Not work in target wasm32-wasi

### ISSUE THREAD

**Issue by sonder-joker** [fizyk20/generic-array#122]
New a cargo project.
```toml
[package]
name = "generic-array-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-array = "0.14.5"
```
then `cargo build --release --target wasm32-wasi`.
                                                                                                                                                   
It would complain so many errors and I couldn't find real reason
